### LIBRARY ###

In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv("Hospinfo.csv")

### Informasi yang di-dapat dan dimasukkan dalam dictionary ###

In [2]:
dict = {
    'attributes': 0,
    'null_attributes': 0,
    'object_attributes': 0,
    'total_records': 0,
    'number_attributes':0
}

In [3]:
dict['attributes'] = list(df.columns.values)
dict['null_attributes'] = list(df.loc[:, df.isnull().any()].columns)
dict['object_attributes'] = list(df.select_dtypes(['object']).columns)
dict['total_records'] = df.shape[0]
dict['number_attributes'] = list(df.select_dtypes(['float64', 'int64']).columns)

### Banyak Record ###

In [23]:
print("Banyak Record =",dict['total_records'])

Banyak Record = 4812

### Nama dan Jumlah Atribut ###

In [22]:
print("Jumlah Atribut =",len(dict['attributes']))

Jumlah Atribut = 29

In [24]:
print("Nama Atribut =",dict['attributes'])

Nama Atribut = ['Provider ID', 'Hospital Name', 'Address', 'City', 'State', 'ZIP Code', 'County Name', 'Phone Number', 'Hospital Type', 'Hospital Ownership', 'Emergency Services', 'Meets criteria for meaningful use of EHRs', 'Hospital overall rating', 'Hospital overall rating footnote', 'Mortality national comparison', 'Mortality national comparison footnote', 'Safety of care national comparison', 'Safety of care national comparison footnote', 'Readmission national comparison', 'Readmission national comparison footnote', 'Patient experience national comparison', 'Patient experience national comparison footnote', 'Effectiveness of care national comparison', 'Effectiveness of care national comparison footnote', 'Timeliness of care national comparison', 'Timeliness of care national comparison footnote', 'Efficient use of medical imaging national comparison', 'Efficient use of medical imaging national comparison footnote', 'Location']

### Jumlah Atribut dengan Tipe Objek ###

In [25]:
print("Jumlah Atribut dengan Tipe Objek =",len(dict ['object_attributes']))

Jumlah Atribut dengan Tipe Objek = 25

### Jumlah Atribute dengan tipe angka ###

In [26]:
print("Jumlah Atribute dengan Tipe Angka =",len(dict['number_attributes']))

Jumlah Atribute dengan Tipe Angka = 3

### Jumlah Atribute yang memiliki null ###

In [27]:
print("Jumlah Atribut yang memiliki Null =",len(dict['null_attributes']))

Jumlah Atribut yang memiliki Null = 10

### Tampilkan rata-rata, standar deviasi, nilai minimum, nilai maksimum, Q1, Q2, dan Q3 dari attribute bertipe angka ###

In [10]:
df.describe()

         Provider ID      ZIP Code  Phone Number
count    4812.000000   4812.000000  4.812000e+03
mean   268294.422901  53990.132377  5.848244e+09
std    157109.340215  26915.916870  2.332196e+09
min     10001.000000    603.000000  9.369338e+08
25%    140185.750000  33015.250000  4.014563e+09
50%    260043.500000  55410.500000  6.053360e+09
75%    390222.250000  76035.500000  7.877574e+09
max    670118.000000  99929.000000  9.898943e+09

### Tampilkan nilai korelasi attribute bertipe angka ###

In [11]:
df.corr()

                    Provider ID  ZIP Code  Phone Number  Emergency Services
Provider ID            1.000000 -0.110463      0.022860            0.044191
ZIP Code              -0.110463  1.000000      0.021930           -0.041373
Phone Number           0.022860  0.021930      1.000000            0.015448
Emergency Services     0.044191 -0.041373      0.015448            1.000000

### Mengubah Atribut Menjadi Desimal ###

### "Sebelum Provider ID diubah" ###

In [12]:
df.dtypes

Provider ID                                                       int64
Hospital Name                                                    object
Address                                                          object
City                                                             object
State                                                            object
ZIP Code                                                          int64
County Name                                                      object
Phone Number                                                      int64
Hospital Type                                                    object
Hospital Ownership                                               object
Emergency Services                                                 bool
Meets criteria for meaningful use of EHRs                        object
Hospital overall rating                                          object
Hospital overall rating footnote                                 object
Mortality national comparison                                    object
Mortality national comparison footnote                           object
Safety of care national comparison                               object
Safety of care national comparison footnote                      object
Readmission national comparison                                  object
Readmission national comparison footnote                         object
Patient experience national comparison                           object
Patient experience national comparison footnote                  object
Effectiveness of care national comparison                        object
Effectiveness of care national comparison footnote               object
Timeliness of care national comparison                           object
Timeliness of care national comparison footnote                  object
Efficient use of medical imaging national comparison             object
Efficient use of medical imaging national comparison footnote    object
Location                                                         object
dtype: object

In [13]:
df['Provider ID'] = df['Provider ID'].astype("float64")

### sesudah Provider ID diubah ###

In [14]:
df.head(10)

,Provider ID,Hospital Name,Address,City,State,ZIP Code,County Name,Phone Number,Hospital Type,Hospital Ownership,...,Readmission national comparison footnote,Patient experience national comparison,Patient experience national comparison footnote,Effectiveness of care national comparison,Effectiveness of care national comparison footnote,Timeliness of care national comparison,Timeliness of care national comparison footnote,Efficient use of medical imaging national comparison,Efficient use of medical imaging national comparison footnote,Location
0,10005.0,MARSHALL MEDICAL CENTER SOUTH,2505 U S HIGHWAY 431 NORTH,BOAZ,AL,35957,MARSHALL,2565938310,Acute Care Hospitals,Government - Hospital District or Authority,...,NaN,Same as the national average,NaN,Same as the national average,NaN,Above the national average,NaN,Below the national average,NaN,"2505 U S HIGHWAY 431 NORTH\nBOAZ, AL\n"
1,10012.0,DEKALB REGIONAL MEDICAL CENTER,200 MED CENTER DRIVE,FORT PAYNE,AL,35968,DE KALB,2568453150,Acute Care Hospitals,Proprietary,...,NaN,Same as the national average,NaN,Same as the national average,NaN,Above the national average,NaN,Same as the national average,NaN,"200 MED CENTER DRIVE\nFORT PAYNE, AL\n"
2,10032.0,WEDOWEE HOSPITAL,209 NORTH MAIN STREET,WEDOWEE,AL,36278,RANDOLPH,2563572111,Acute Care Hospitals,Government - Hospital District or Authority,...,NaN,Not Available,Results are not available for this reporting p...,Same as the national average,NaN,Same as the national average,NaN,Not Available,Results are not available for this reporting p...,"209 NORTH MAIN STREET\nWEDOWEE, AL\n"
3,10095.0,HALE COUNTY HOSPITAL,508 GREEN STREET,GREENSBORO,AL,36744,HALE,3346243024,Acute Care Hospitals,Government - Local,...,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Below the national average,NaN,Same as the national average,NaN,Not Available,Results are not available for this reporting p...,"508 GREEN STREET\nGREENSBORO, AL\n"
4,10131.0,CRESTWOOD MEDICAL CENTER,ONE HOSPITAL DR SE,HUNTSVILLE,AL,35801,MADISON,2568823100,Acute Care Hospitals,Proprietary,...,NaN,Same as the national average,NaN,Same as the national average,NaN,Same as the national average,NaN,Same as the national average,NaN,"ONE HOSPITAL DR SE\nHUNTSVILLE, AL\n"
5,11304.0,CHOCTAW GENERAL HOSPITAL,"401 VANITY FAIR LANE, PO BOX 618",BUTLER,AL,36904,CHOCTAW,2054599100,Critical Access Hospitals,Voluntary non-profit - Private,...,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Same as the national average,NaN,Not Available,Results are not available for this reporting p...,"401 VANITY FAIR LANE, PO BOX 618\nBUTLER, AL\n"
6,20018.0,YUKON KUSKOKWIM DELTA REG HOSPITAL,PO BOX 287,BETHEL,AK,99559,BETHEL,9075436300,Acute Care Hospitals,Tribal,...,NaN,Below the national average,NaN,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,"PO BOX 287\nBETHEL, AK\n"
7,21308.0,NORTON SOUND REGIONAL HOSPITAL,1000 GREG KRUSCHEK AVENUE (P O BOX 966),NOME,AK,99762,NOME,9074433311,Critical Access Hospitals,Tribal,...,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,"1000 GREG KRUSCHEK AVENUE (P O BOX 966)\nNOME,..."
8,21309.0,KANAKANAK HOSPITAL,P O BOX 130,DILLINGHAM,AK,99576,DILLINGHAM,9078425201,Critical Access Hospitals,Voluntary non-profit - Private,...,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,"P O BOX 130\nDILLINGHAM, AK\n"
9,21310.0,MANIILAQ HEALTH CENTER,PO BOX 43,KOTZEBUE,AK,99752,NORTHWEST ARCTIC,9074423321,Critical Access Hospitals,Tribal,...,Data are shown only for hospitals that partici...,Not Available,Data are shown only for hospitals that partici...,Not Available,Data are shown only for hospitals that partici...,Not Available,Data are shown only for hospitals that partici...,Not Available,Data are shown only for hospitals that partici...,"PO BOX 43\nKOTZEBUE, AK\n"

In [15]:
df.dtypes

Provider ID                                                      float64
Hospital Name                                                     object
Address                                                           object
City                                                              object
State                                                             object
ZIP Code                                                           int64
County Name                                                       object
Phone Number                                                       int64
Hospital Type                                                     object
Hospital Ownership                                                object
Emergency Services                                                  bool
Meets criteria for meaningful use of EHRs                         object
Hospital overall rating                                           object
Hospital overall rating footnote                                  object
Mortality national comparison                                     object
Mortality national comparison footnote                            object
Safety of care national comparison                                object
Safety of care national comparison footnote                       object
Readmission national comparison                                   object
Readmission national comparison footnote                          object
Patient experience national comparison                            object
Patient experience national comparison footnote                   object
Effectiveness of care national comparison                         object
Effectiveness of care national comparison footnote                object
Timeliness of care national comparison                            object
Timeliness of care national comparison footnote                   object
Efficient use of medical imaging national comparison              object
Efficient use of medical imaging national comparison footnote     object
Location                                                          object
dtype: object

### Tampilkan 10 record pertama dari attribute bertipe angka ###

In [16]:
dh = df.select_dtypes(include=np.number)
dh.head(10)

   Provider ID  ZIP Code  Phone Number
0      10005.0     35957    2565938310
1      10012.0     35968    2568453150
2      10032.0     36278    2563572111
3      10095.0     36744    3346243024
4      10131.0     35801    2568823100
5      11304.0     36904    2054599100
6      20018.0     99559    9075436300
7      21308.0     99762    9074433311
8      21309.0     99576    9078425201
9      21310.0     99752    9074423321

### Simpan dataset dengan attribute bertipe angka ke dalam file CSV ###

In [19]:
variabel= df.select_dtypes(include=np.number)
variabel.to_csv("info.csv")